INFERENCE_PARAMETERS:
  general:
    PRE_NAME: 'bert-base-uncased'
    MAX_LENGTH: 512
    tokenizer_path: 'api_file/tokenizer_folder/'
    PRE_MODEL: 'tf-serving/pre-trained-model/'
    HEADS: 1
    H1: [['question_title', 'question_body'],['answer']]
    H2: []